language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x ./gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

#deploy 명령어가 실행되기 전에 수행될 코드

before_deploy:
  - zip -r aws-webservice * #CodeDeploy는 Jar 파일을 인식못해서 알집으로 압축
  - mkdir -p deploy #deploy라는 디렉토리 생성
  - mv aws-webservice.zip deploy/aws-webservice.zip

#AWS S3에서 만든 사용자 액세스 키
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: aws-webservice-build # s3버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private #zip 파일 접근을 private로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: ture

  - project: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:  $AWS_SECRET_KEY
    bucket: aws-webservice-build # s3버킷
    key: aws-webservice.zip
    application: aws-webservice #AWS deploy에서 등록한 애플리케이션
    deployment_group: aws-webservice-group # AWS deploy에서 등록한 배포그룹
    region: ap-northeast-2
    wait-until-deployed: true

#CI 실행완료 시 메일로 알람
notifications:
  email:
    recipients:
      - ksky9230@naver.com

