language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x ./gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

#deploy 명령어가 실행되기 전에 수행될 코드

before_deploy:
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/aws-webservice.zip

#AWS S3에서 만든 사용자 액세스 키
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: aws-webservice-build # s3버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private #zip 파일 접근을 private로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: ture

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:  $AWS_SECRET_KEY
    bucket: aws-webservice-build # s3버킷
    key: aws-webservice.zip
    bundle_type: zip
    application: aws-webservice #AWS deploy에서 등록한 애플리케이션
    deployment_group: aws-webservice-group # AWS deploy에서 등록한 배포그룹
    region: ap-northeast-2
    wait-until-deployed: true

#CI 실행완료 시 메일로 알람
notifications:
  email:
    recipients:
      - ksky9230@naver.com

